version: '3.8'

services:
  # Jaeger all-in-one (includes collector, query, UI)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: himalytix-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"   # Zipkin compact
      - "6831:6831/udp"   # Jaeger compact thrift
      - "6832:6832/udp"   # Jaeger binary thrift
      - "5778:5778"       # Config
      - "16686:16686"     # UI
      - "14250:14250"     # Model proto
      - "14268:14268"     # Jaeger thrift
      - "14269:14269"     # Admin
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "9411:9411"       # Zipkin
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge
