site_name: ERPNextGen Documentation
theme:
  name: material
nav:
  - Home: index.md
  - 'Configuration Schemas':
    - 'UI Schema': 'schemas/ui.md'
    - 'Validation Schema': 'schemas/validation.md'
    - 'Workflow Schema': 'schemas/workflow.md'
  - 'API Reference':
    - 'Suggest Endpoint': 'api/suggest.md'
plugins:
  - search
  - mermaid2
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences